import { expect, test, type Locator, type Page } from '@playwright/test'
import type { DocumentBlockDraft } from '../src/shared/contracts'
import { withElectronApp } from './helpers/electron'

const block = (type: DocumentBlockDraft['type'], content: string): DocumentBlockDraft => ({ type, content, checked: false, depth: 0 })

async function openEditor(page: Page, title: string, blocks: DocumentBlockDraft[]) {
  const id = await page.evaluate(async ({ title, blocks }) => {
    const { id } = await window.knowbook.createDocument(null)
    await window.knowbook.updateDocument(id, { title, summary: '', blocks })
    return id
  }, { title, blocks })
  await page.reload()
  await page.locator('.tree-button', { hasText: title }).first().click()
  await expect(page.locator('textarea.block-inline-textarea')).toHaveCount(blocks.length)
  return page.locator('textarea.block-inline-textarea')
}

async function caret(editor: Locator, position: number) {
  await editor.focus()
  await editor.evaluate((element, position) => {
    const input = element as HTMLTextAreaElement
    input.setSelectionRange(position, position)
    input.dispatchEvent(new Event('select', { bubbles: true }))
  }, position)
}

test('slash suggestions take arrows before block navigation and leave modifiers and IME intact @electron', async () => {
  await withElectronApp(async ({ page }) => {
    const editors = await openEditor(page, 'Slash keyboard priority', [block('paragraph', 'Before'), block('paragraph', '/'), block('paragraph', 'After')])
    const editor = editors.nth(1)
    await caret(editor, 1)
    await editor.press('End')
    const menu = page.locator('.floating-slash-command-panel')
    const active = menu.locator('.slash-command-item-active .slash-command-id')
    await expect(active).toHaveText('/text')
    await editor.press('ArrowDown')
    await expect(editor).toBeFocused()
    await expect(active).toHaveText('/h1')
    await editor.press('ArrowUp')
    await expect(editor).toBeFocused()
    await expect(active).toHaveText('/text')
    await editor.press('ArrowUp')
    await expect(active).toHaveText('/delete')
    await editor.press('ArrowDown')
    await expect(active).toHaveText('/text')

    await editor.evaluate(element => {
      element.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true }))
      for (const key of ['ArrowDown', 'Enter', 'Tab', 'Escape']) {
        element.dispatchEvent(new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true, isComposing: true }))
      }
      element.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true }))
      element.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', keyCode: 229, bubbles: true, cancelable: true }))
    })
    await expect(active).toHaveText('/text')
    await expect(editor).toHaveValue('/')
    await editor.press('Shift+Tab')
    await expect(editor).toHaveValue('/')
    await expect(page.locator('.markdown-format-toolbar button').last()).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(editor).toBeFocused()
    await editor.press('ArrowDown')
    await editor.press('Enter')
    await expect(editor).toHaveClass(/type-heading-1/)
    await expect(editor).toHaveValue('')
    await expect(editor).toBeFocused()
    await expect(menu).toHaveCount(0)
  })
})

test('link suggestions support keyboard acceptance, dismissal and mouse focus restoration @electron', async () => {
  await withElectronApp(async ({ page }) => {
    const editors = await openEditor(page, 'Link keyboard priority', [block('paragraph', 'First target'), block('paragraph', '[['), block('paragraph', 'Second target')])
    const editor = editors.nth(1)
    await caret(editor, 2)
    await editor.press('End')
    const menu = page.locator('.link-helper-panel')
    const active = menu.locator('.relation-chip-active')
    await expect(active).toContainText('First target')
    await editor.press('ArrowDown')
    await expect(editor).toBeFocused()
    await expect(active).toContainText('[[')
    await editor.press('ArrowUp')
    await expect(active).toContainText('First target')
    await editor.evaluate(element => {
      element.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true }))
      element.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true, isComposing: true }))
      element.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true }))
    })
    await expect(editor).toHaveValue('[[')
    await expect(active).toContainText('First target')
    await editor.press('Tab')
    await expect(editor).toHaveValue(/^\[\[[^\]]+\]\]$/)
    await expect(editor).toBeFocused()
    const inserted = await editor.inputValue()
    expect(await editor.evaluate(element => (element as HTMLTextAreaElement).selectionStart)).toBe(inserted.length)
    await expect(menu).toHaveCount(0)
    await editor.press('Control+z')
    await expect(editor).toHaveValue('[[')
    await expect(menu).toBeVisible()
    await editor.press('Escape')
    await expect(menu).toHaveCount(0)
    await expect(editor).toHaveValue('[[')
    await expect(editor).toBeFocused()
    await editor.pressSequentially(' canceled [[')
    await expect(menu).toBeVisible()
    await editor.press('Escape')
    await expect(menu).toHaveCount(0)
    await editor.fill('[[First')
    await menu.locator('.relation-chip').filter({ hasText: 'First target' }).first().click()
    await expect(editor).toHaveValue(inserted)
    await expect(editor).toBeFocused()
    expect(await editor.evaluate(element => (element as HTMLTextAreaElement).selectionStart)).toBe(inserted.length)
  })
})

test('rapid typing followed by split undoes only the structural operation @electron', async () => {
  await withElectronApp(async ({ page }) => {
    const editors = await openEditor(page, 'Split history boundary', [block('paragraph', 'Original')])
    // Pause renderer timers so the 600 ms input debounce cannot hide a missing checkpoint.
    await page.clock.install()
    await page.clock.pauseAt(new Date())
    await editors.first().fill('Original appended')
    await caret(editors.first(), 8)
    await editors.first().press('Alt+Enter')
    await expect(editors).toHaveCount(2)
    await expect(editors.first()).toHaveValue('Original')
    await expect(editors.nth(1)).toHaveValue(' appended')
    await page.keyboard.press('Control+z')
    await expect(editors).toHaveCount(1)
    await expect(editors.first()).toHaveValue('Original appended')
    await expect(editors.first()).toBeFocused()
    await page.keyboard.press('Control+Shift+z')
    await expect(editors).toHaveCount(2)
    await expect(editors.nth(1)).toHaveValue(' appended')
  })
})

test('rapid typing followed by list indentation and downgrade keeps text during undo @electron', async () => {
  await withElectronApp(async ({ page }) => {
    const editors = await openEditor(page, 'List history boundary', [block('bulleted-list', 'Parent'), block('bulleted-list', 'Original')])
    await page.clock.install()
    await page.clock.pauseAt(new Date())
    const editor = editors.nth(1)
    await editor.fill('Original appended')
    await editor.press('Tab')
    const row = page.locator('.block-editor-row').nth(1)
    await expect(row).toHaveCSS('padding-left', '24px')
    await page.keyboard.press('Control+z')
    await page.clock.runFor(1)
    await expect(row).toHaveCSS('padding-left', '0px')
    await expect(editor).toHaveValue('Original appended')
    await page.keyboard.press('Control+Shift+z')
    await page.clock.runFor(1)
    await expect(row).toHaveCSS('padding-left', '24px')
    await page.keyboard.press('Control+z')
    await page.clock.runFor(1)
    await editor.fill('Retained before downgrade')
    await caret(editor, 0)
    await editor.press('Backspace')
    await expect(editor).toHaveClass(/type-paragraph/)
    await page.keyboard.press('Control+z')
    await expect(editor).toHaveClass(/type-bulleted-list/)
    await expect(editor).toHaveValue('Retained before downgrade')
    await page.keyboard.press('Control+Shift+z')
    await expect(editor).toHaveClass(/type-paragraph/)
    await expect(editor).toHaveValue('Retained before downgrade')
  })
})
