import { expect, test, type Page } from '@playwright/test'
import { mkdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { DocumentBlockDraft } from '../src/shared/contracts'
import { withElectronApp, uiText } from './helpers/electron'

async function openDocument(page: Page, title: string, blocks: DocumentBlockDraft[]) {
  const id = await page.evaluate(async ({ title, blocks }) => {
    const { id } = await window.knowbook.createDocument(null)
    await window.knowbook.updateDocument(id, { title, summary: '', blocks })
    return id
  }, { title, blocks })
  await page.reload()
  await page.locator('.tree-button', { hasText: title }).first().click()
  return id
}

test('table cells support formatting, spreadsheet paste, structure, undo and file round trips @electron', async () => {
  test.setTimeout(150_000)
  await withElectronApp(async ({ app, page, tempRoot }) => {
    const source = '| A | B |\n| :--- | ---: |\n| a\\|b | `c\\|d` | ignored |\n| second | value |'
    const id = await openDocument(page, 'Editable grid', [{ type: 'table', content: source, checked: false, depth: 0 },
      { type: 'paragraph', content: 'After table', checked: false, depth: 0 }])
    const grid = page.getByRole('grid', { name: uiText('Editable table', '可编辑表格') })
    const cell = (row: number, column: number) => grid.locator(`[data-row="${row}"][data-column="${column}"]`)
    const editCell = async (row: number, column: number) => { await cell(row, column).focus(); await cell(row, column).press('Enter'); return grid.locator('textarea') }
    await expect(grid).toBeVisible()
    await cell(1, 0).click()
    await expect(grid.locator('textarea')).toHaveValue('a|b')
    await grid.locator('textarea').evaluate((input) => {
      input.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true }))
      input.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', isComposing: true, bubbles: true, cancelable: true }))
      input.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true }))
    })
    await expect(grid.locator('textarea')).toHaveValue('a|b')
    await grid.locator('textarea').fill('修改 | literal')
    await grid.locator('textarea').evaluate((input) => (input as HTMLTextAreaElement).setSelectionRange(0, 2))
    await grid.locator('textarea').press('Control+b')
    await expect(grid.locator('textarea')).toHaveValue('**修改** | literal')
    expect(await grid.locator('textarea').evaluate(input => [(input as HTMLTextAreaElement).selectionStart, (input as HTMLTextAreaElement).selectionEnd])).toEqual([2, 4])
    await grid.locator('textarea').press('Control+i')
    await expect(grid.locator('textarea')).toHaveValue('***修改*** | literal')
    await grid.locator('textarea').press('Control+z')
    await expect(grid.locator('textarea')).toHaveValue('**修改** | literal')
    await grid.locator('textarea').press('Alt+F10')
    await expect(page.getByRole('button', { name: uiText('Bold', '粗体'), exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(grid.locator('textarea')).toBeFocused()
    await page.keyboard.press('Control+z')
    await expect(grid.locator('textarea')).toHaveValue('修改 | literal')
    await page.keyboard.press('Control+Shift+z')
    await expect(grid.locator('textarea')).toHaveValue('**修改** | literal')
    await grid.locator('textarea').press('Tab')
    await expect(grid.locator('textarea')).toHaveValue('`c|d`')
    await grid.locator('textarea').fill('^[单元脚注]')
    await grid.locator('textarea').press('Escape')
    await expect(cell(1, 0).locator('strong')).toHaveText('修改')
    await expect(page.locator('.markdown-footnotes')).toContainText('单元脚注')
    await page.getByRole('combobox', { name: uiText('Column alignment', '列对齐') }).selectOption('center')
    await expect(cell(1, 1)).toHaveCSS('text-align', 'center')
    const pasteTarget = await editCell(1, 1)
    await pasteTarget.evaluate((input) => {
      const clipboard = new DataTransfer(); clipboard.setData('text/plain', '甲\t乙\n1\t2')
      input.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: clipboard }))
    })
    await expect(grid.locator('thead th')).toHaveCount(3)
    await grid.locator('textarea').press('Escape')
    await expect(cell(1, 2)).toHaveText('乙')
    await expect(cell(2, 2)).toHaveText('2')
    await expect(page.locator('.markdown-footnotes')).toHaveCount(0)
    await page.getByRole('button', { name: uiText('Insert row above', '上方插入行'), exact: true }).click()
    await expect(grid.locator('tbody tr')).toHaveCount(3)
    await page.getByRole('button', { name: uiText('Delete row', '删除行'), exact: true }).click()
    await expect(grid.locator('tbody tr')).toHaveCount(2)
    await page.keyboard.press('Control+z')
    await expect(grid.locator('tbody tr')).toHaveCount(3)
    await page.keyboard.press('Control+Shift+z')
    await expect(grid.locator('tbody tr')).toHaveCount(2)
    await page.getByRole('button', { name: uiText('Insert column right', '右侧插入列'), exact: true }).click()
    await expect(grid.locator('thead th')).toHaveCount(4)
    await page.getByRole('button', { name: uiText('Delete column', '删除列'), exact: true }).click()
    await expect(grid.locator('thead th')).toHaveCount(3)
    await editCell(2, 2)
    await grid.locator('textarea').press('Tab')
    await expect(grid.locator('tbody tr')).toHaveCount(3)
    await grid.locator('textarea').fill('新增行')
    await grid.locator('textarea').press('Escape')
    expect(await cell(3, 0).evaluate(element => document.activeElement === element)).toBe(true)
    await page.keyboard.press('Tab')
    expect(await page.evaluate(() => Boolean(document.activeElement?.closest('[role="grid"]')))).toBe(false)
    const following = page.locator('textarea.type-paragraph').last()
    await following.focus()
    await following.evaluate((input) => (input as HTMLTextAreaElement).setSelectionRange(0, 0))
    await following.press('ArrowUp')
    await expect(page.locator('textarea.type-table')).toBeVisible()
    await expect(page.locator('textarea.type-table')).toBeFocused()
    const editedSource = await page.locator('textarea.type-table').inputValue()
    expect(editedSource).toContain('**修改** \\| literal')
    expect(editedSource).toContain('| ignored |')
    expect(editedSource).toContain('新增行')
    await expect.poll(async () => (await page.evaluate((id) => window.knowbook.getDocumentDetail(id), id))?.blocks[0].content).toBe(editedSource)
    await page.reload(); await page.locator('.tree-button', { hasText: 'Editable grid' }).first().click()
    await expect(cell(3, 0)).toHaveText('新增行')
    await page.screenshot({ path: 'test-results/markdown-table-editing.png' })

    const directory = join(tempRoot, 'table-export'); mkdirSync(directory)
    const filePath = join(directory, 'Editable grid.md')
    await app.evaluate(({ dialog }, { directory, filePath }) => {
      dialog.showSaveDialog = (async () => ({ canceled: false, filePath })) as typeof dialog.showSaveDialog
      dialog.showOpenDialog = (async () => ({ canceled: false, filePaths: [directory] })) as typeof dialog.showOpenDialog
      dialog.showMessageBox = (async () => ({ response: 0, checkboxChecked: false })) as typeof dialog.showMessageBox
    }, { directory, filePath })
    await page.locator('.document-header-more-button').click()
    await page.locator('.document-header-action-menu').getByRole('button', { name: uiText('Save MD', '导出 Markdown') }).click()
    await expect.poll(() => { try { return readFileSync(filePath, 'utf8') } catch { return '' } }).toContain(editedSource)
    await page.evaluate(() => window.knowbook.restoreBackupFromFolder())
    await page.reload(); await page.locator('.tree-button', { hasText: 'Editable grid' }).first().click()
    await expect(cell(3, 0)).toHaveText('新增行')
    await page.locator('.document-view-toggle').click()
    await expect(page.locator('.document-reading-row.type-table strong')).toHaveText('修改')
    await expect(page.locator('.document-reading-row.type-table')).not.toContainText('ignored')
  })
})

test('reading tasks remain interactive in nested lists, callouts and footnotes with undo and reload @electron', async () => {
  await withElectronApp(async ({ page }) => {
    const id = await openDocument(page, 'Interactive tasks', [{ type: 'paragraph', content: '', checked: false, depth: 0 }])
    const source = '# **Tasks** $x$\n\n- [ ] Parent\n  - [x] Child\n\n* [ ] Complex\n\n  > Nested quote\n  > - [ ] Quoted task\n\n  continuation\n\n> [!tip]+ Work\n> - [ ] Callout task\n\nNote[^n]\n\n[^n]: - [ ] Footnote task\n\n3. Numbered\n4. Last\n\n`- [ ] code`'
    await page.locator('textarea.block-inline-textarea').first().evaluate((input, source) => {
      input.focus(); const clipboard = new DataTransfer(); clipboard.setData('text/plain', source)
      input.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: clipboard }))
    }, source)
    await page.keyboard.press('Control+z')
    await expect(page.locator('textarea.block-inline-textarea').first()).toHaveValue('')
    await page.locator('.document-view-toggle').click()
    await page.keyboard.press('Control+Shift+z')
    await expect(page.getByRole('checkbox', { name: /Quoted task/ })).toHaveCount(0)
    await page.locator('.document-view-toggle').click()
    await page.keyboard.press('Control+Shift+z')
    await page.locator('.document-view-toggle').click()
    await expect(page.locator('ul.markdown-reading-list-tight').first()).toBeVisible()
    await expect(page.locator('ul.markdown-reading-list-loose').first()).toBeVisible()
    await expect(page.locator('ol.markdown-reading-list')).toHaveAttribute('start', '3')
    await expect(page.locator('.reading-list-marker').filter({ hasText: /^3\.$/ })).toHaveCount(1)
    const quoted = page.getByRole('checkbox', { name: /Quoted task/ })
    await page.keyboard.press('Control+z')
    await expect(quoted).toBeVisible()
    await quoted.check()
    await expect(quoted).toBeChecked()
    await page.keyboard.press('Control+z')
    await expect(quoted).not.toBeChecked()
    await page.keyboard.press('Control+z')
    await expect(quoted).toBeVisible()
    await page.keyboard.press('Control+Shift+z')
    await expect(quoted).toBeChecked()
    await page.getByRole('checkbox', { name: /Callout task/ }).check()
    await page.getByRole('checkbox', { name: /Footnote task/ }).check()
    const parent = page.locator('.document-reading-row.type-todo').filter({ hasText: 'Parent' }).getByRole('checkbox')
    await parent.check()
    const parentRow = page.locator('.document-reading-row.type-todo').filter({ hasText: 'Parent' })
    await parentRow.locator('.reading-collapse').click()
    await expect(page.locator('.document-reading-row').filter({ hasText: /^Child$/ })).toHaveCount(0)
    await parentRow.locator('.reading-collapse').click()
    await expect(page.locator('.document-reading-row.type-todo').filter({ hasText: 'Child' })).toBeVisible()
    await expect.poll(async () => (await page.evaluate((id) => window.knowbook.getDocumentDetail(id), id))?.blocks.some((block) => block.content.includes('[x] Footnote task'))).toBe(true)
    await page.screenshot({ path: 'test-results/markdown-interactive-tasks.png' })
    await page.reload(); await page.locator('.tree-button', { hasText: 'Interactive tasks' }).first().click()
    if (await page.locator('.document-reading-row').count() === 0) await page.locator('.document-view-toggle').click()
    for (const label of ['Quoted task', 'Callout task', 'Footnote task']) await expect(page.getByRole('checkbox', { name: new RegExp(label) })).toBeChecked()
    await expect(page.locator('.document-reading-row.type-todo').filter({ hasText: 'Parent' }).getByRole('checkbox')).toBeChecked()
    const detail = (await page.evaluate((id) => window.knowbook.getDocumentDetail(id), id))!
    expect(detail.blocks.find((block) => block.content.includes('`- [ ] code`'))?.content).toContain('`- [ ] code`')
  })
})

test('format shortcuts and toolbar preserve Unicode selections, IME and undo @electron', async () => {
  await withElectronApp(async ({ page }) => {
    const id = await openDocument(page, 'Format selection', [{ type: 'paragraph', content: 'Draft 中文 😀 text', checked: false, depth: 0 }])
    const editor = page.locator('textarea.block-inline-textarea').first()
    await editor.focus()
    await editor.evaluate((input) => (input as HTMLTextAreaElement).setSelectionRange(6, 11))
    await editor.press('Control+b')
    await expect(editor).toHaveValue('Draft **中文 😀** text')
    expect(await editor.evaluate(input => [(input as HTMLTextAreaElement).selectionStart, (input as HTMLTextAreaElement).selectionEnd])).toEqual([8, 13])
    await editor.press('Alt+F10')
    await expect(page.getByRole('button', { name: uiText('Bold', '粗体'), exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(editor).toBeFocused()
    await editor.press('Shift+Tab')
    await page.keyboard.press('Home')
    await page.keyboard.press('ArrowRight')
    await expect(page.getByRole('button', { name: uiText('Italic', '斜体'), exact: true })).toBeFocused()
    await page.keyboard.press('Enter')
    await expect(editor).toHaveValue('Draft ***中文 😀*** text')
    expect(await editor.evaluate(input => [(input as HTMLTextAreaElement).selectionStart, (input as HTMLTextAreaElement).selectionEnd])).toEqual([9, 14])
    await editor.press('Control+i')
    await expect(editor).toHaveValue('Draft **中文 😀** text')
    await page.getByRole('button', { name: uiText('Strikethrough', '删除线'), exact: true }).click()
    await expect(editor).toHaveValue('Draft **~~中文 😀~~** text')
    await page.keyboard.press('Control+z')
    await expect(editor).toHaveValue('Draft **中文 😀** text')
    await editor.evaluate((input) => {
      input.dispatchEvent(new KeyboardEvent('keydown', { key: 'b', ctrlKey: true, isComposing: true, bubbles: true, cancelable: true }))
    })
    await expect(editor).toHaveValue('Draft **中文 😀** text')
    await editor.evaluate((input) => (input as HTMLTextAreaElement).setSelectionRange(8, 13))
    await editor.press('Control+Shift+k')
    await expect(editor).toHaveValue('Draft **[中文 😀](https://)** text')
    await page.keyboard.insertText('https://example.com')
    await expect(editor).toHaveValue('Draft **[中文 😀](https://example.com)** text')
    await expect.poll(async () => (await page.evaluate((id) => window.knowbook.getDocumentDetail(id), id))?.blocks[0].content).toBe('Draft **[中文 😀](https://example.com)** text')
    await page.reload(); await page.locator('.tree-button', { hasText: 'Format selection' }).first().click()
    await page.locator('.document-view-toggle').click()
    await expect(page.locator('.document-reading-row strong .inline-link')).toHaveText('中文 😀')
  })
})

test('advanced slash templates insert useful content without replacing existing text @electron', async () => {
  await withElectronApp(async ({ page }) => {
    await openDocument(page, 'Insert templates', [{ type: 'paragraph', content: 'Keep this ', checked: false, depth: 0 }])
    const editor = page.locator('textarea.block-inline-textarea').first()
    await editor.fill('Keep this\n/table'); await editor.press('End'); await editor.press('Enter')
    await expect(editor).toHaveValue('Keep this\n')
    await expect(page.getByRole('grid', { name: uiText('Editable table', '可编辑表格') })).toBeVisible()
    await page.keyboard.press('Control+z')
    await expect(page.locator('textarea.type-table')).toHaveCount(0)
    for (const [command, expected] of [['mermaid', 'flowchart LR'], ['callout', '[!note]'], ['toc', '[TOC]']]) {
      await editor.fill('/' + command); await editor.press('End'); await editor.press('Enter')
      await expect.poll(() => editor.inputValue()).toContain(expected)
      await page.keyboard.press('Control+z')
    }
  })
})

test('Chromium IME commit and cancel preserve multilingual Markdown and uppercase shortcuts @electron', async () => {
  await withElectronApp(async ({ page }) => {
    const initial = '中文 日本語 한국어 العربية 👩🏽‍💻'
    const id = await openDocument(page, 'Composition quality', [{ type: 'paragraph', content: initial, checked: false, depth: 0 }])
    const editor = page.locator('textarea.block-inline-textarea').first()
    const cdp = await page.context().newCDPSession(page)
    await editor.focus(); await editor.press('End')
    await cdp.send('Input.imeSetComposition', { text: '拼音候选', selectionStart: 4, selectionEnd: 4 })
    await expect(editor).toHaveValue(initial + '拼音候选')
    await cdp.send('Input.imeSetComposition', { text: '输入完成', selectionStart: 4, selectionEnd: 4 })
    await cdp.send('Input.insertText', { text: '输入完成' })
    await expect(editor).toHaveValue(initial + '输入完成')
    await expect(page.locator('textarea.block-inline-textarea')).toHaveCount(1)
    await cdp.send('Input.imeSetComposition', { text: '取消候选', selectionStart: 4, selectionEnd: 4 })
    await cdp.send('Input.imeSetComposition', { text: '', selectionStart: 0, selectionEnd: 0 })
    await expect(editor).toHaveValue(initial + '输入完成')
    await editor.evaluate((input) => (input as HTMLTextAreaElement).setSelectionRange(0, 2))
    await editor.press('Control+B')
    await expect(editor).toHaveValue('**中文**' + initial.slice(2) + '输入完成')
    await editor.press('Control+Z')
    await expect(editor).toHaveValue(initial + '输入完成')
    await editor.press('Control+Shift+Z')
    const expected = '**中文**' + initial.slice(2) + '输入完成'
    await expect(editor).toHaveValue(expected)
    await expect.poll(async () => (await page.evaluate((id) => window.knowbook.getDocumentDetail(id), id))?.blocks[0].content).toBe(expected)
    await cdp.detach()
    await page.reload(); await page.locator('.tree-button', { hasText: 'Composition quality' }).first().click()
    await expect(editor).toHaveValue(expected)
    await page.locator('.document-view-toggle').click()
    await expect(page.locator('.document-reading-row strong')).toHaveText('中文')
    await expect(page.locator('.document-reading-row')).toContainText(initial.slice(2) + '输入完成')
  })
})

test('cross-paragraph formatting keeps Markdown structure through toggle, undo, save and reload @electron', async () => {
  await withElectronApp(async ({ page }) => {
    const source = '第一段 中文 😀\n软换行\n\n第二段 日本語\n\n- [ ] Task\n\n```ts\nconst untouched = 1\n```'
    const formatted = '**第一段 中文 😀\n软换行**\n\n**第二段 日本語**\n\n- [ ] **Task**\n\n```ts\nconst untouched = 1\n```'
    const id = await openDocument(page, 'Paragraph formatting', [{ type: 'paragraph', content: source, checked: false, depth: 0 }])
    const editor = page.locator('textarea.block-inline-textarea').first()
    await editor.focus(); await editor.press('Control+a'); await editor.press('Control+b')
    await expect(editor).toHaveValue(formatted)
    await editor.press('Control+b')
    await expect(editor).toHaveValue(source)
    await editor.press('Control+z')
    await expect(editor).toHaveValue(formatted)
    await editor.press('Control+z')
    await expect(editor).toHaveValue(source)
    await editor.press('Control+Shift+z')
    await expect(editor).toHaveValue(formatted)
    await expect.poll(async () => (await page.evaluate((id) => window.knowbook.getDocumentDetail(id), id))?.blocks[0].content).toBe(formatted)
    await page.reload(); await page.locator('.tree-button', { hasText: 'Paragraph formatting' }).first().click()
    await expect(editor).toHaveValue(formatted)
    await page.locator('.document-view-toggle').click()
    await expect(page.locator('.document-reading-row strong')).toHaveCount(3)
    await expect(page.getByRole('checkbox', { name: /Task/ })).not.toBeChecked()
    await expect(page.locator('.document-reading-row pre')).toContainText('const untouched = 1')
  })
})
