import { expect, test } from '@playwright/test'
import { ensureDocumentMetadataEditor, uiText, withElectronApp } from './helpers/electron'

test('shortcut help searches actions and key combinations, filters contexts and fits both themes @electron', async ({}, testInfo) => {
  await withElectronApp(async ({ page }) => {
    const trigger = page.getByRole('button', { name: uiText('Keyboard shortcuts', '快捷键帮助'), exact: true })
    await expect(trigger).toBeInViewport()
    await trigger.click()
    const help = page.getByRole('dialog', { name: uiText('Keyboard shortcuts', '快捷键帮助'), exact: true })
    const search = help.getByRole('searchbox', { name: uiText('Search shortcuts', '搜索快捷键') })
    await expect(search).toBeFocused()
    await expect(help.locator('[data-shortcut-id="source-apply"]')).toContainText(/Apply source changes|应用源码更改/)
    await page.screenshot({ path: testInfo.outputPath('shortcut-help-light.png') })
    await search.fill('Ctrl+K')
    await expect(help.locator('[data-shortcut-id]')).toHaveCount(1)
    await expect(help.locator('[data-shortcut-id="search"]')).toBeVisible()
    await search.fill('Ctrl+Shift+F')
    await expect(help.locator('[data-shortcut-id]')).toHaveCount(1)
    await expect(help.locator('[data-shortcut-id="workspace-search"]')).toBeVisible()
    await search.fill('⌘+Shift+D')
    await expect(help.locator('[data-shortcut-id="block-duplicate"]')).toBeVisible()
    await search.fill('加粗')
    await expect(help.locator('[data-shortcut-id="format-bold"]')).toBeVisible()
    await search.fill('Ctrl+Enter')
    await expect(help.locator('[data-shortcut-id]')).toHaveCount(3)
    for (const id of ['quick-capture-save', 'search-document', 'block-insert']) {
      await expect(help.locator(`[data-shortcut-id="${id}"]`)).toBeVisible()
    }
    await help.getByRole('combobox', { name: uiText('Shortcut category', '快捷键分类') }).selectOption('search')
    await expect(help.locator('[data-shortcut-id]')).toHaveCount(1)
    await search.fill('not-a-real-shortcut')
    await expect(help.getByText(uiText('No matching shortcuts', '没有匹配的快捷键'))).toBeVisible()
    await help.getByRole('button', { name: uiText('Clear filters', '清除筛选') }).click()
    await expect(search).toHaveValue('')
    await expect(search).toBeFocused()
    await page.keyboard.press('Control+k')
    await expect(page.locator('.global-search-modal')).toHaveCount(0)
    await page.keyboard.press('Control+2')
    await expect(page.locator('.page-documents')).toBeVisible()
    await page.setViewportSize({ width: 420, height: 640 })
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark' })
    expect(await help.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    await expect(help.getByRole('button', { name: uiText('Close keyboard shortcuts', '关闭快捷键帮助') })).toBeInViewport()
    await page.screenshot({ path: testInfo.outputPath('shortcut-help-dark-narrow.png') })
    await page.keyboard.press('Escape')
    await expect(help).toHaveCount(0)
    await expect(trigger).toBeFocused()
    await page.getByRole('button', { name: uiText('Collapse sidebar', '收起左侧栏'), exact: true }).click()
    await expect(trigger).toBeInViewport()
    await trigger.click()
    await expect(help).toBeVisible()
    await page.keyboard.press('F1')
    await expect(help).toHaveCount(0)
    await expect(trigger).toBeFocused()
  })
})

test('help restores a nested source editor and displays macOS modifier names @electron', async () => {
  await withElectronApp(async ({ page }) => {
    await page.getByRole('button', { name: uiText('More actions', '更多操作') }).click()
    await page.locator('.document-header-action-menu').getByRole('button', { name: uiText('Edit Markdown source', '编辑 Markdown 源码') }).click()
    const source = page.locator('.document-markdown-source')
    const editor = source.locator('.cm-content')
    await editor.fill('Retained source while viewing keyboard help')
    await page.evaluate(() => Object.defineProperty(navigator, 'platform', { configurable: true, value: 'MacIntel' }))
    await page.keyboard.press('F1')
    const help = page.locator('.shortcut-help-dialog')
    await expect(help).toBeVisible()
    await help.getByRole('searchbox').fill('Ctrl+B')
    await expect(help.locator('[data-shortcut-id="format-bold"] kbd').first()).toHaveText('⌘')
    await expect(help.locator('footer')).toContainText('Option')
    await page.keyboard.press('Escape')
    await expect(help).toHaveCount(0)
    await expect(source).toBeVisible()
    await expect(editor).toBeFocused()
    await expect(editor).toHaveText('Retained source while viewing keyboard help')
  })
})

test('F1 works across pages and command palette opens help without losing the editor draft @electron', async () => {
  await withElectronApp(async ({ page }) => {
    const help = page.getByRole('dialog', { name: uiText('Keyboard shortcuts', '快捷键帮助'), exact: true })
    await page.keyboard.press('F1')
    await expect(help).toBeVisible()
    await page.keyboard.press('Escape')
    for (const [en, zh] of [['Documents', '文档'], ['Dashboard', '总览'], ['Database', '数据库'], ['AI Assistant', 'AI 助手'], ['Plugins', '插件中心'], ['Settings', '配置中心']]) {
      const nav = page.getByTitle(uiText(en, zh), { exact: true })
      await nav.click()
      await page.keyboard.press('F1')
      await expect(help).toBeVisible()
      const close = help.getByRole('button', { name: uiText('Close keyboard shortcuts', '关闭快捷键帮助') })
      await close.focus()
      await page.keyboard.press('Shift+Tab')
      await expect(help.locator('.shortcut-help-results')).toBeFocused()
      await page.keyboard.press('Tab')
      await expect(close).toBeFocused()
      await page.keyboard.press('Escape')
      await expect(help).toHaveCount(0)
      await expect(nav).toBeFocused()
    }
    await page.getByTitle(uiText('Documents', '文档'), { exact: true }).click()
    await ensureDocumentMetadataEditor(page)
    const title = page.locator('.document-summary-card .editor-input').first()
    await title.fill('Shortcut help draft')
    await title.dispatchEvent('compositionstart')
    await page.keyboard.press('F1')
    await expect(help).toHaveCount(0)
    await title.dispatchEvent('compositionend')
    await page.keyboard.press('F1')
    await expect(help).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(title).toBeFocused()
    await expect(title).toHaveValue('Shortcut help draft')
    await page.keyboard.press('Control+Shift+p')
    await page.locator('.global-search-input').fill('> keyboard shortcuts')
    await page.locator('.global-search-input').press('Enter')
    await expect(help).toBeVisible()
    await expect(page.locator('.global-search-modal')).toHaveCount(0)
    await page.keyboard.press('Escape')
    await expect(title).toHaveValue('Shortcut help draft')
    await page.getByRole('button', { name: uiText('More actions', '更多操作') }).click()
    await page.locator('.document-header-action-menu').getByRole('button', { name: uiText('Delete', '删除') }).click()
    const confirmation = page.getByRole('alertdialog')
    await expect(confirmation).toBeVisible()
    await page.keyboard.press('F1')
    await expect(help).toHaveCount(0)
    await expect(confirmation).toBeVisible()
    await page.keyboard.press('Escape')
  })
})
